/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForStudentsRouteImport } from './routes/for-students'
import { Route as ForParentsRouteImport } from './routes/for-parents'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EliteRouteImport } from './routes/elite'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DailyPuzzleRouteImport } from './routes/daily-puzzle'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as AiTutorGuideRouteImport } from './routes/ai-tutor-guide'
import { Route as AiTutorRouteImport } from './routes/ai-tutor'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonDayRouteImport } from './routes/lesson.$day'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForStudentsRoute = ForStudentsRouteImport.update({
  id: '/for-students',
  path: '/for-students',
  getParentRoute: () => rootRouteImport,
} as any)
const ForParentsRoute = ForParentsRouteImport.update({
  id: '/for-parents',
  path: '/for-parents',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteRoute = EliteRouteImport.update({
  id: '/elite',
  path: '/elite',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyPuzzleRoute = DailyPuzzleRouteImport.update({
  id: '/daily-puzzle',
  path: '/daily-puzzle',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTutorGuideRoute = AiTutorGuideRouteImport.update({
  id: '/ai-tutor-guide',
  path: '/ai-tutor-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTutorRoute = AiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonDayRoute = LessonDayRouteImport.update({
  id: '/lesson/$day',
  path: '/lesson/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/ai-tutor': typeof AiTutorRoute
  '/ai-tutor-guide': typeof AiTutorGuideRoute
  '/certificates': typeof CertificatesRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/curriculum': typeof CurriculumRoute
  '/daily-puzzle': typeof DailyPuzzleRoute
  '/dashboard': typeof DashboardRoute
  '/elite': typeof EliteRoute
  '/faq': typeof FaqRoute
  '/for-parents': typeof ForParentsRoute
  '/for-students': typeof ForStudentsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/lesson/$day': typeof LessonDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/ai-tutor': typeof AiTutorRoute
  '/ai-tutor-guide': typeof AiTutorGuideRoute
  '/certificates': typeof CertificatesRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/curriculum': typeof CurriculumRoute
  '/daily-puzzle': typeof DailyPuzzleRoute
  '/dashboard': typeof DashboardRoute
  '/elite': typeof EliteRoute
  '/faq': typeof FaqRoute
  '/for-parents': typeof ForParentsRoute
  '/for-students': typeof ForStudentsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/lesson/$day': typeof LessonDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/ai-tutor': typeof AiTutorRoute
  '/ai-tutor-guide': typeof AiTutorGuideRoute
  '/certificates': typeof CertificatesRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/curriculum': typeof CurriculumRoute
  '/daily-puzzle': typeof DailyPuzzleRoute
  '/dashboard': typeof DashboardRoute
  '/elite': typeof EliteRoute
  '/faq': typeof FaqRoute
  '/for-parents': typeof ForParentsRoute
  '/for-students': typeof ForStudentsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/lesson/$day': typeof LessonDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/ai-tutor'
    | '/ai-tutor-guide'
    | '/certificates'
    | '/chat'
    | '/contact'
    | '/curriculum'
    | '/daily-puzzle'
    | '/dashboard'
    | '/elite'
    | '/faq'
    | '/for-parents'
    | '/for-students'
    | '/login'
    | '/onboarding'
    | '/parent'
    | '/pricing'
    | '/privacy'
    | '/progress'
    | '/resources'
    | '/services'
    | '/settings'
    | '/signup'
    | '/solutions'
    | '/lesson/$day'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/ai-tutor'
    | '/ai-tutor-guide'
    | '/certificates'
    | '/chat'
    | '/contact'
    | '/curriculum'
    | '/daily-puzzle'
    | '/dashboard'
    | '/elite'
    | '/faq'
    | '/for-parents'
    | '/for-students'
    | '/login'
    | '/onboarding'
    | '/parent'
    | '/pricing'
    | '/privacy'
    | '/progress'
    | '/resources'
    | '/services'
    | '/settings'
    | '/signup'
    | '/solutions'
    | '/lesson/$day'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/ai-tutor'
    | '/ai-tutor-guide'
    | '/certificates'
    | '/chat'
    | '/contact'
    | '/curriculum'
    | '/daily-puzzle'
    | '/dashboard'
    | '/elite'
    | '/faq'
    | '/for-parents'
    | '/for-students'
    | '/login'
    | '/onboarding'
    | '/parent'
    | '/pricing'
    | '/privacy'
    | '/progress'
    | '/resources'
    | '/services'
    | '/settings'
    | '/signup'
    | '/solutions'
    | '/lesson/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  AiTutorRoute: typeof AiTutorRoute
  AiTutorGuideRoute: typeof AiTutorGuideRoute
  CertificatesRoute: typeof CertificatesRoute
  ChatRoute: typeof ChatRoute
  ContactRoute: typeof ContactRoute
  CurriculumRoute: typeof CurriculumRoute
  DailyPuzzleRoute: typeof DailyPuzzleRoute
  DashboardRoute: typeof DashboardRoute
  EliteRoute: typeof EliteRoute
  FaqRoute: typeof FaqRoute
  ForParentsRoute: typeof ForParentsRoute
  ForStudentsRoute: typeof ForStudentsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ParentRoute: typeof ParentRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgressRoute: typeof ProgressRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SolutionsRoute: typeof SolutionsRoute
  LessonDayRoute: typeof LessonDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-students': {
      id: '/for-students'
      path: '/for-students'
      fullPath: '/for-students'
      preLoaderRoute: typeof ForStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-parents': {
      id: '/for-parents'
      path: '/for-parents'
      fullPath: '/for-parents'
      preLoaderRoute: typeof ForParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite': {
      id: '/elite'
      path: '/elite'
      fullPath: '/elite'
      preLoaderRoute: typeof EliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-puzzle': {
      id: '/daily-puzzle'
      path: '/daily-puzzle'
      fullPath: '/daily-puzzle'
      preLoaderRoute: typeof DailyPuzzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tutor-guide': {
      id: '/ai-tutor-guide'
      path: '/ai-tutor-guide'
      fullPath: '/ai-tutor-guide'
      preLoaderRoute: typeof AiTutorGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tutor': {
      id: '/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/ai-tutor'
      preLoaderRoute: typeof AiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$day': {
      id: '/lesson/$day'
      path: '/lesson/$day'
      fullPath: '/lesson/$day'
      preLoaderRoute: typeof LessonDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  AiTutorRoute: AiTutorRoute,
  AiTutorGuideRoute: AiTutorGuideRoute,
  CertificatesRoute: CertificatesRoute,
  ChatRoute: ChatRoute,
  ContactRoute: ContactRoute,
  CurriculumRoute: CurriculumRoute,
  DailyPuzzleRoute: DailyPuzzleRoute,
  DashboardRoute: DashboardRoute,
  EliteRoute: EliteRoute,
  FaqRoute: FaqRoute,
  ForParentsRoute: ForParentsRoute,
  ForStudentsRoute: ForStudentsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ParentRoute: ParentRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProgressRoute: ProgressRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SolutionsRoute: SolutionsRoute,
  LessonDayRoute: LessonDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
